""" Module for the Users entity schema."""
from logogram.common.execute_command import execute_command


def create_user_table():
    """ Create users table on PostgreSQL"""
    command = (
        """
        CREATE TABLE IF NOT EXISTS "users" (
        "id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        "password" varchar(128) NOT NULL,
        "email" text NOT NULL UNIQUE,
        "is_superuser" boolean DEFAULT 'false' NOT NULL,
        "is_staff" boolean DEFAULT 'false' NOT NULL,
        "first_name" varchar(20) NULL,
        "last_name" varchar(20) NULL,
        "date_joined" date DEFAULT NOW() NOT NULL,
        "last_login" date NULL
        )
        """)
    execute_command(command)
