""" Module for the Flashcards entity schema."""
from logogram.common.execute_command import execute_command


def create_flashcards_table():
    """ Create flashcards table on PostgreSQL"""
    command = (
        """
        CREATE TABLE IF NOT EXISTS "flashcards" (
        "id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        "name" text NOT NULL,
        "description" text NULL,
        "users" integer REFERENCES "users" ON DELETE CASCADE
        )
        """)
    execute_command(command)
