version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.0

      - image: circleci/postgres:11
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle-test_test

    working_directory: ~/repo

    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - restore_cache:
      # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}

      - run:
          name: install dependencies
          command: |
            pipenv install -d

      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.7/site-packages"

      - run:
          name: run tests
          environment:
            DATABASE_USER: root
            DATABASE_NAME: circle-test_test
            DATABASE_PASSWORD: ""
            POSTGRES_IP: 127.0.0.1
            DATABASE_PORT: 5432
          command: |
            cd src/database_playbook/
            pipenv run coverage run --rcfile=../../.coveragerc manage.py test
            pipenv run coverage report --rcfile=../../.coveragerc
            pipenv run coverage html --rcfile=../../.coveragerc
            export COVERALLS_REPO_TOKEN=${COVERALLS_REPO_TOKEN}
            pipenv run coveralls --rcfile=../../.coveragerc

      - store_artifacts:
          path: src/database_playbook/htmlcov
          destination: test-reports
